name: Veracode Build Java Maven Application

on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
      ref:
        required: true
        type: string
      token:
        required: true
        type: string
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.ref }}
        token: ${{ inputs.token }}
    - uses: actions/setup-java@v3
      with:
        java-version: 8
        distribution: temurin
    - name: Cache Maven Dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
    - name: Build with Maven
      run: mvn clean package
      
    - name: Identify the Artifact
      id: identify
      run: |
        mkdir -p ./veracode_artifacts
        packaging_type=$(mvn help:evaluate -Dexpression=project.packaging -q -DforceStdout)
        artifact_name=$(mvn help:evaluate -Dexpression=project.build.finalName -q -DforceStdout)
        artifact_extension=".jar"

        if [ "$packaging_type" = "war" ]; then
          artifact_extension=".war"
        elif [ "$packaging_type" = "ear" ]; then
          artifact_extension=".ear"
        fi

        mvn_artifact=$(mvn help:evaluate -Dexpression=project.build.directory -q -DforceStdout)/"$artifact_name$artifact_extension"
        echo "Artifact path: $mvn_artifact"
        mv $mvn_artifact ./veracode_artifacts/
        # find . -type f -name "*.jar" -exec mv {} ./veracode_artifacts/ \;
        # find . -type f -name "*.war" -exec mv {} ./veracode_artifacts/ \;
        # find . -type f -name "*.ear" -exec mv {} ./veracode_artifacts/ \;
        
    - uses: actions/upload-artifact@v3
      with:
        name: veracode-artifact
        path: ./veracode_artifacts/
